### ISSUE TITLE
"Add stock to display" continues to be shown

### ISSUE THREAD

**Issue by neoneye** [ThasianX/DivRise#4]
Nice project you have.

I have added the "Apple" stock, but the text continues to be shown on-top.

![Simulator Screen Shot - iPhone 8 - 2020-01-08 at 00 51 05](https://user-images.githubusercontent.com/147971/71938863-0caf2a00-31b1-11ea-8146-9be310ab2fc4.png)

**Comment by ThasianX** [comment]
Works for me. Run it again - Xcode 11
